backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "projets"
    label: "Projets"
    folder: "content/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string", hint: "Utilise une nouvelle ligne pour revenir à la ligne dans le titre." }
      - { label: "Sous-titre", name: "soustitre", widget: "string" }
      - { label: "Premier paragraphe", name: "paragraphe1", widget: "text" }
      - { label: "Deuxième paragraphe", name: "paragraphe2", widget: "text", required: false }
      - label: "Galerie"
        name: "galerie"
        widget: "list"
        required: false
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Texte alternatif", name: "alt", widget: "string" }
